// Configuration for data source
// Primary: reads from /public/remoteData.json generated by `npm run sync`

export const DATA_SOURCE = {
    type: 'json' as const,
    // This file is generated locally by `npm run sync` and served from /public
    url: '/remoteData.json',
    apiKey: ''
};
